# Generated by Django 3.0.9 on 2020-08-30 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_galleryevent_imageupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageupload',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.GalleryEvent'),
        ),
    ]
