# Generated by Django 3.0.9 on 2020-08-30 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_imageupload_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryevent',
            name='images',
        ),
    ]
